spring:
  profiles:
    active: "prod"
  jpa:
    properties:
      hibernate:
        metadata_builder_contributor: com.example.testtask.configuration.SqlFunctionsMetadataBuilderContributor
    hibernate:
      ddl-auto: none

    database-platform: org.hibernate.dialect.PostgreSQLDialect
#  datasource:
#    url: "jdbc:postgresql://localhost:54320/dbTest"
#    username: user
#    password: pass
#    initialization-mode: always

#
